version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aluradb
  app:
    build: .
    ports:
      - 8070:8080
    depends_on:
      - db
